name: PR Title Check
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.11.0"

      - name: Get Dependencies
        run: dart pub get

      - name: Validate Title of PR
        run: echo "${{github.event.pull_request.title}}" | dart run commitlint_cli
